#!/bin/bash

# Initalize gillespy. Set GILLESPYHOME and GILLESPYPATH
if [ "$0"="-bash" -o "$0"="bash" ];then
    #echo "this file is being sourced"
    EXE_FILE="${BASH_SOURCE[0]}";
else
    EXE_FILE=$0
fi
#echo "EXE_FILE = $EXE_FILE"
##############
if [ -L "$EXE_FILE" ]; then
  MY_PATH=$(cd $(dirname $(readlink $EXE_FILE)); pwd)
else
  MY_PATH=$(cd $(dirname $EXE_FILE); pwd)
fi
export GILLESPYHOME=$MY_PATH
export PYTHONPATH="$PYTHONPATH:$GILLESPYHOME"
export C_INCLUDE_PATH=/usr/lib/openmpi/include
#echo "GILLESPYHOME=$GILLESPYHOME"
#echo "PYTHONPATH=$PYTHONPATH"
export C_INCLUDE_PATH=/usr/lib/openmpi/include

